In [1]:
import sys
import os

sys.path.append(os.path.abspath("../src"))

import pandas as pd
import numpy as np
from utils import audit, load_and_split_city, diagnose_missing, impute_time_series

# 1. Load dữ liệu cho Delhi
delhi = load_and_split_city("Delhi")
print("=== DELHI (audit gốc) ===")
display(audit(delhi).sort_values("pct_missing", ascending=False))

# 2. Load dữ liệu cho Gurugram
gurugram = load_and_split_city("Gurugram")
print("\n=== GURUGRAM (audit gốc) ===")
display(audit(gurugram).sort_values("pct_missing", ascending=False))

=== DELHI (audit gốc) ===

                     dtype  n_missing  pct_missing  n_unique
Xylene             float64        781         38.9       387
SO2                float64        110          5.5      1284
O3                 float64         84          4.2      1684
PM10               float64         77          3.8      1888
AQI                float64         10          0.5       471
AQI_Bucket             str         10          0.5         6
NH3                float64          9          0.4      1604
NO                 float64          2          0.1      1745
PM2.5              float64          2          0.1      1913
NO2                float64          2          0.1      1764
Date        datetime64[us]          0          0.0      2009
City                   str          0          0.0         1
NOx                float64          0          0.0      1848
CO                 float64          0          0.0       454
Benzene            float64          0          0.0       743
Toluene            float64          0          0.0      1505

=== GURUGRAM (audit gốc) ===

                     dtype  n_missing  pct_missing  n_unique
NH3                float64       1560         92.9       119
Xylene             float64       1560         92.9       104
PM10               float64        939         55.9       732
Toluene            float64        610         36.3       390
NOx                float64        452         26.9      1017
Benzene            float64        442         26.3       350
AQI                float64        226         13.5       421
AQI_Bucket             str        226         13.5         6
SO2                float64        175         10.4      1024
PM2.5              float64        154          9.2      1461
NO                 float64        138          8.2      1150
NO2                float64        136          8.1      1217
O3                 float64        116          6.9      1372
CO                 float64        109          6.5       293
Date        datetime64[us]          0          0.0      1679
City                   str          0          0.0         1

## Bước 2: Xử lý missing values

Cách làm:

1. **Săn missing ẩn** — kiểm tra các chuỗi giá trị `0` liên tiếp dài (≥3 ngày): nồng độ khí thực tế hiếm khi đứng yên ở đúng 0 nhiều ngày liền, nhiều khả năng là cảm biến bị treo (flatline), không phải giá trị thật → chuyển các chuỗi này thành `NaN`.
2. **Không coi mọi missing như nhau** — nhiều cột có khối thiếu **liên tục hàng chục–hàng nghìn ngày** (cảm biến chưa lắp/hỏng dài hạn), khác hẳn với thiếu rải rác vài ngày. Missing phụ thuộc vào `Date` (biến quan sát được) → cơ chế **MAR**, không phải MCAR.
3. **Chỉ nội suy khoảng trống ngắn** (mặc định ≤14 ngày) — khoảng trống dài **CHỦ Ý để nguyên `NaN`**, không bịa số cho hàng trăm/nghìn ngày không có dữ liệu thật.

In [2]:
# Chẩn đoán: cột nào nên nội suy trực tiếp, cột nào có khối lớn cần cẩn thận, cột nào nên đề xuất DROP
print("=== DELHI - diagnose_missing ===")
display(diagnose_missing(delhi))

print("\n=== GURUGRAM - diagnose_missing ===")
display(diagnose_missing(gurugram))

=== DELHI - diagnose_missing ===

,pct_missing,block_ratio_%,action
col,,,
PM2.5,0.1,100.0,nội suy trực tiếp (missing quá ít)
PM10,3.8,75.0,"có khối lớn — chỉ nội suy phần rải rác, giữ Na..."
NO,0.1,100.0,nội suy trực tiếp (missing quá ít)
NO2,0.1,100.0,nội suy trực tiếp (missing quá ít)
NOx,0.0,NaN,giữ nguyên
NH3,0.4,22.0,nội suy trực tiếp (missing quá ít)
CO,0.0,NaN,giữ nguyên
SO2,5.5,74.0,"có khối lớn — chỉ nội suy phần rải rác, giữ Na..."
O3,4.2,96.0,"có khối lớn — chỉ nội suy phần rải rác, giữ Na..."
Benzene,0.0,NaN,giữ nguyên
Toluene,0.0,NaN,giữ nguyên
Xylene,38.9,78.0,"có khối lớn — chỉ nội suy phần rải rác, giữ Na..."

=== GURUGRAM - diagnose_missing ===

,pct_missing,block_ratio_%,action
col,,,
PM2.5,9.2,36,nội suy trực tiếp
PM10,55.9,81,"có khối lớn — chỉ nội suy phần rải rác, giữ Na..."
NO,8.2,38,nội suy trực tiếp
NO2,8.1,38,nội suy trực tiếp
NOx,26.9,72,"có khối lớn — chỉ nội suy phần rải rác, giữ Na..."
NH3,92.9,100,ĐỀ XUẤT DROP (gần như không có dữ liệu thật)
CO,6.5,41,nội suy trực tiếp
SO2,10.4,17,nội suy trực tiếp
O3,6.9,32,nội suy trực tiếp
Benzene,26.3,76,"có khối lớn — chỉ nội suy phần rải rác, giữ Na..."
Toluene,36.3,55,"có khối lớn — chỉ nội suy phần rải rác, giữ Na..."
Xylene,92.9,100,ĐỀ XUẤT DROP (gần như không có dữ liệu thật)

**Đọc bảng trên:** `NH3` và `Xylene` ở Gurugram đều ~93% missing và gần như toàn bộ nằm trong 1 khối duy nhất (block_ratio ~100%). Ban đầu mình đề xuất DROP cả 2 cột cho Gurugram — nhưng đã kiểm tra lại số liệu thật của 6 thành phố còn lại trong file gốc (xem bảng dưới) và sửa lại quyết định:

| City | NH3 %missing | Xylene %missing |
|---|---|---|
| Delhi | 0.4% | 38.9% |
| Gurugram | 92.9% | 92.9% |
| Lucknow | 50.0% | 100.0% |
| Jaipur | 1.3% | 100.0% |
| Bengaluru | 10.1% | 100.0% |
| Amritsar | 3.4% | 17.4% |
| Chennai | 23.0% | 100.0% |
| Hyderabad | 17.9% | 6.3% |

- **NH3**: đa số thành phố có dữ liệu khá tốt (0.4%–23%), chỉ Gurugram và Lucknow là tệ → **giữ lại cột này cho cả 8 thành phố**, drop sẽ làm mất dữ liệu tốt của 6 thành phố kia.
- **Xylene**: **4/8 thành phố thiếu 100%**, cả Delhi lẫn Gurugram đều thiếu nặng (38.9%, 92.9%) → **đề xuất DROP cột này cho TẤT CẢ 8 thành phố**, chỉ Amritsar/Hyderabad có dữ liệu tạm ổn nhưng không đủ để giữ cột cho cả bộ dữ liệu chung.

`PM10` ở Gurugram còn 55.9% với khối lớn chiếm 81% — vẫn giữ lại (không đủ điều kiện DROP theo ngưỡng 90%) nhưng cần lưu ý rõ trong báo cáo là dữ liệu không đầy đủ.

⚠️ **Cần chốt với nhóm:** đề xuất DROP `Xylene` cho cả 8 thành phố (không riêng Gurugram), giữ `NH3`. Và ngưỡng `max_short_gap=14` ngày cho nội suy.

In [3]:
delhi_clean, delhi_flat_changed = impute_time_series(delhi, "Delhi", drop_cols=["Xylene"])
print()
gurugram_clean, gurugram_flat_changed = impute_time_series(
    gurugram, "Gurugram", drop_cols=["Xylene"]  # ĐỀ XUẤT - đã đồng ý với nhóm chưa?
)

--- Xử lý Missing Values cho Delhi ---
  - CO: phát hiện 84 ngày flatline (0 liên tục >= 3 ngày) -> NaN
  - Benzene: phát hiện 3 ngày flatline (0 liên tục >= 3 ngày) -> NaN
  - Toluene: phát hiện 105 ngày flatline (0 liên tục >= 3 ngày) -> NaN
  - Xylene: phát hiện 128 ngày flatline (0 liên tục >= 3 ngày) -> NaN
  - Đã xoá cột (đề xuất, cần nhóm đồng ý): ['Xylene']
  => Còn 349 ô missing SAU xử lý (CHỦ Ý giữ NaN ở khối trống dài, không bịa số)

--- Xử lý Missing Values cho Gurugram ---
  - NOx: phát hiện 23 ngày flatline (0 liên tục >= 3 ngày) -> NaN
  - CO: phát hiện 30 ngày flatline (0 liên tục >= 3 ngày) -> NaN
  - Benzene: phát hiện 264 ngày flatline (0 liên tục >= 3 ngày) -> NaN
  - Toluene: phát hiện 253 ngày flatline (0 liên tục >= 3 ngày) -> NaN
  - Đã xoá cột (đề xuất, cần nhóm đồng ý): ['Xylene']
  => Còn 4603 ô missing SAU xử lý (CHỦ Ý giữ NaN ở khối trống dài, không bịa số)

In [4]:
# Kiểm chứng: so sánh % missing trước / sau cho từng cột
pollutant_cols = ['PM2.5','PM10','NO','NO2','NOx','NH3','CO','SO2','O3','Benzene','Toluene','Xylene']

def compare_missing(before_df, after_df, cols):
    before = before_df[cols].isna().mean() * 100
    after_cols = [c for c in cols if c in after_df.columns]
    after = after_df[after_cols].isna().mean() * 100
    return pd.DataFrame({'truoc_%': before.round(1), 'sau_%': after.reindex(before.index).round(1)})

print("=== DELHI: truoc/sau ===")
display(compare_missing(delhi, delhi_clean, pollutant_cols + ['AQI']))

print("\n=== GURUGRAM: truoc/sau ===")
display(compare_missing(gurugram, gurugram_clean, pollutant_cols + ['AQI']))

=== DELHI: truoc/sau ===

         truoc_%  sau_%
PM2.5        0.1    0.0
PM10         3.8    2.2
NO           0.1    0.0
NO2          0.1    0.0
NOx          0.0    0.0
NH3          0.4    0.0
CO           0.0    3.5
SO2          5.5    4.0
O3           4.2    3.3
Benzene      0.0    0.0
Toluene      0.0    3.8
Xylene      38.9    NaN
AQI          0.5    0.5

=== GURUGRAM: truoc/sau ===

         truoc_%  sau_%
PM2.5        9.2    3.8
PM10        55.9   51.5
NO           8.2    2.3
NO2          8.1    2.3
NOx         26.9   21.3
NH3         92.9   92.9
CO           6.5    1.8
SO2         10.4    1.4
O3           6.9    1.4
Benzene     26.3   35.9
Toluene     36.3   46.2
Xylene      92.9    NaN
AQI         13.5   13.5

**Lưu ý:** một vài cột (CO, Toluene ở Delhi; Benzene, Toluene ở Gurugram) có `sau_%` **cao hơn** `truoc_%` — không phải lỗi, mà vì bước phát hiện flatline vừa lộ ra các đoạn `0` giả trước đây bị tính nhầm là "có dữ liệu". Đây là phát hiện thật, cần ghi vào cleaning log để báo cáo với nhóm/giảng viên, không nên ỉm đi.

In [5]:
os.makedirs("../data/interim", exist_ok=True)
delhi_clean.to_csv("../data/interim/delhi_after_missing.csv", index=False)
gurugram_clean.to_csv("../data/interim/gurugram_after_missing.csv", index=False)
print("Đã lưu data/interim/delhi_after_missing.csv và data/interim/gurugram_after_missing.csv")
print("Delhi:", delhi_clean.shape, " | Gurugram:", gurugram_clean.shape)

Đã lưu data/interim/delhi_after_missing.csv và data/interim/gurugram_after_missing.csv
Delhi: (2009, 28)  | Gurugram: (1679, 28)

## Bước 3: Outliers & validity checks (W4)

Quyết định đã chọn cho bước này (an toàn, chưa xoá gì):
- Phát hiện bằng **IQR**, tính ngưỡng **riêng theo từng tháng dương lịch** (gộp các năm) — tránh gắn nhầm mùa ô nhiễm cao (đốt rơm rạ tháng 10-11, Diwali) thành outlier.
- **Chỉ đánh dấu** (`<cột>_is_outlier`), **không xoá/sửa giá trị gốc** — quyết định giữ/xoá để dành cho lúc gộp đủ 8 thành phố, đối chiếu xem outlier là lỗi cảm biến hay sự kiện thật.
- Không áp dụng cho `AQI` — đây là biến kết quả, các giá trị AQI cao chính là điều nhóm muốn phân tích, không phải lỗi.
- Kèm theo bộ **validity checks** cơ bản (không âm, ngày không ở tương lai, AQI khớp AQI_Bucket) để kiểm tra nhanh sau mỗi lần xử lý.

In [6]:
from utils import flag_outliers_iqr, validity_checks

delhi_outliers = flag_outliers_iqr(delhi_clean)
gurugram_outliers = flag_outliers_iqr(gurugram_clean)

for name, df in [("DELHI", delhi_outliers), ("GURUGRAM", gurugram_outliers)]:
    outlier_cols = [c for c in df.columns if c.endswith('_is_outlier')]
    print(f"=== {name}: số ngày bị đánh dấu outlier mỗi cột ===")
    display(df[outlier_cols].sum().sort_values(ascending=False))

=== DELHI: số ngày bị đánh dấu outlier mỗi cột ===

CO_is_outlier         211
O3_is_outlier         120
NO_is_outlier          88
NH3_is_outlier         85
SO2_is_outlier         84
NOx_is_outlier         75
NO2_is_outlier         72
Toluene_is_outlier     61
PM2.5_is_outlier       55
Benzene_is_outlier     55
PM10_is_outlier        40
dtype: int64

=== GURUGRAM: số ngày bị đánh dấu outlier mỗi cột ===

NO_is_outlier         141
PM2.5_is_outlier      111
SO2_is_outlier         96
CO_is_outlier          78
NO2_is_outlier         65
NOx_is_outlier         50
Benzene_is_outlier     43
Toluene_is_outlier     38
PM10_is_outlier        19
O3_is_outlier          19
NH3_is_outlier          6
dtype: int64

In [7]:
print("=== DELHI: validity checks ===")
display(validity_checks(delhi_outliers))

print("\n=== GURUGRAM: validity checks ===")
display(validity_checks(gurugram_outliers))

=== DELHI: validity checks ===

                       rule  n_violations
0            PM2.5 không âm             0
1             PM10 không âm             0
2               NO không âm             0
3              NO2 không âm             0
4              NOx không âm             0
5              NH3 không âm             0
6               CO không âm             0
7              SO2 không âm             0
8               O3 không âm             0
9          Benzene không âm             0
10         Toluene không âm             0
11             AQI không âm             0
12   Date không ở tương lai             0
13  AQI_Bucket khớp với AQI             0

=== GURUGRAM: validity checks ===

                       rule  n_violations
0            PM2.5 không âm             0
1             PM10 không âm             0
2               NO không âm             0
3              NO2 không âm             0
4              NOx không âm             0
5              NH3 không âm             0
6               CO không âm             0
7              SO2 không âm             0
8               O3 không âm             0
9          Benzene không âm             0
10         Toluene không âm             0
11             AQI không âm             0
12   Date không ở tương lai             0
13  AQI_Bucket khớp với AQI             0

In [8]:
delhi_outliers.to_csv("../data/interim/delhi_after_outliers.csv", index=False)
gurugram_outliers.to_csv("../data/interim/gurugram_after_outliers.csv", index=False)
print("Đã lưu data/interim/delhi_after_outliers.csv và data/interim/gurugram_after_outliers.csv")
print("Delhi:", delhi_outliers.shape, " | Gurugram:", gurugram_outliers.shape)

Đã lưu data/interim/delhi_after_outliers.csv và data/interim/gurugram_after_outliers.csv
Delhi: (2009, 39)  | Gurugram: (1679, 39)

## Bước 4: Consistency & Deduplicate (nốt phần còn lại của W4)

Với Delhi/Gurugram, audit đầu tiên đã cho thấy không có vấn đề, nhưng vẫn viết
thành hàm dùng chung trong `utils.py` — vì 6 thành phố còn lại trong nhóm CÓ
THỂ gặp lỗi thật (tên thành phố gõ sai, dòng trùng...) mà không có code kiểm
tra thì sẽ không phát hiện ra.

In [9]:
from utils import check_consistency, check_duplicates

for name, df in [("DELHI", delhi_outliers), ("GURUGRAM", gurugram_outliers)]:
    issues = check_consistency(df)
    n_dup = check_duplicates(df)
    print(f"=== {name} ===")
    print("Consistency issues:", issues if issues else "Không có vấn đề")
    print("Số dòng trùng (City+Date):", n_dup)
    print()

=== DELHI ===
Consistency issues: Không có vấn đề
Số dòng trùng (City+Date): 0

=== GURUGRAM ===
Consistency issues: Không có vấn đề
Số dòng trùng (City+Date): 0

## Bước 5: Re-validate — checkpoint sau W3 + W4

⚠️ **Đính chính:** đây CHƯA phải bản cuối cùng để nộp `data/processed/`. Theo
đúng slide W5, "Transform & merge" vẫn thuộc Chapter 2 "Data cleaning" —
`data/processed/` + cleaning log hoàn chỉnh chỉ nộp SAU KHI xong W5 (EX5.3).
Bản dưới đây là checkpoint sau W3 (missing) + W4 (outliers, consistency,
dedup), lưu tạm vào `data/interim/` để dùng tiếp cho W5.

In [10]:
print("=== DELHI: audit cuối cùng ===")
display(audit(delhi_outliers).sort_values('pct_missing', ascending=False))

print("\n=== GURUGRAM: audit cuối cùng ===")
display(audit(gurugram_outliers).sort_values('pct_missing', ascending=False))

=== DELHI: audit cuối cùng ===

                              dtype  n_missing  pct_missing  n_unique
SO2                         float64         81          4.0      1313
Toluene                     float64         77          3.8      1533
CO                          float64         70          3.5       468
O3                          float64         67          3.3      1701
PM10                        float64         44          2.2      1921
AQI                         float64         10          0.5       471
AQI_Bucket                      str         10          0.5         6
NOx                         float64          0          0.0      1848
NO2                         float64          0          0.0      1766
NO                          float64          0          0.0      1747
PM2.5                       float64          0          0.0      1915
Date                 datetime64[us]          0          0.0      2009
City                            str          0          0.0         1
NH3                         float64          0          0.0      1612
Benzene                     float64          0          0.0       745
PM2.5_was_missing              bool          0          0.0         2
PM10_was_missing               bool          0          0.0         2
NO_was_missing                 bool          0          0.0         2
NO2_was_missing                bool          0          0.0         2
NOx_was_missing                bool          0          0.0         1
NH3_was_missing                bool          0          0.0         2
CO_was_missing                 bool          0          0.0         2
SO2_was_missing                bool          0          0.0         2
O3_was_missing                 bool          0          0.0         2
Benzene_was_missing            bool          0          0.0         2
Toluene_was_missing            bool          0          0.0         2
Xylene_was_missing             bool          0          0.0         2
AQI_was_missing                bool          0          0.0         2
PM2.5_is_outlier               bool          0          0.0         2
PM10_is_outlier                bool          0          0.0         2
NO_is_outlier                  bool          0          0.0         2
NO2_is_outlier                 bool          0          0.0         2
NOx_is_outlier                 bool          0          0.0         2
NH3_is_outlier                 bool          0          0.0         2
CO_is_outlier                  bool          0          0.0         2
SO2_is_outlier                 bool          0          0.0         2
O3_is_outlier                  bool          0          0.0         2
Benzene_is_outlier             bool          0          0.0         2
Toluene_is_outlier             bool          0          0.0         2

=== GURUGRAM: audit cuối cùng ===

                              dtype  n_missing  pct_missing  n_unique
NH3                         float64       1560         92.9       119
PM10                        float64        865         51.5       806
Toluene                     float64        775         46.2       477
Benzene                     float64        603         35.9       446
NOx                         float64        357         21.3      1131
AQI                         float64        226         13.5       421
AQI_Bucket                      str        226         13.5         6
PM2.5                       float64         63          3.8      1551
NO                          float64         38          2.3      1246
NO2                         float64         38          2.3      1307
CO                          float64         31          1.8       385
O3                          float64         23          1.4      1460
SO2                         float64         24          1.4      1162
Date                 datetime64[us]          0          0.0      1679
City                            str          0          0.0         1
PM2.5_was_missing              bool          0          0.0         2
PM10_was_missing               bool          0          0.0         2
NO_was_missing                 bool          0          0.0         2
NO2_was_missing                bool          0          0.0         2
NOx_was_missing                bool          0          0.0         2
NH3_was_missing                bool          0          0.0         2
CO_was_missing                 bool          0          0.0         2
SO2_was_missing                bool          0          0.0         2
O3_was_missing                 bool          0          0.0         2
Benzene_was_missing            bool          0          0.0         2
Toluene_was_missing            bool          0          0.0         2
Xylene_was_missing             bool          0          0.0         2
AQI_was_missing                bool          0          0.0         2
PM2.5_is_outlier               bool          0          0.0         2
PM10_is_outlier                bool          0          0.0         2
NO_is_outlier                  bool          0          0.0         2
NO2_is_outlier                 bool          0          0.0         2
NOx_is_outlier                 bool          0          0.0         2
NH3_is_outlier                 bool          0          0.0         2
CO_is_outlier                  bool          0          0.0         2
SO2_is_outlier                 bool          0          0.0         2
O3_is_outlier                  bool          0          0.0         2
Benzene_is_outlier             bool          0          0.0         2
Toluene_is_outlier             bool          0          0.0         2

In [11]:
delhi_outliers.to_csv("../data/interim/delhi_after_w4.csv", index=False)
gurugram_outliers.to_csv("../data/interim/gurugram_after_w4.csv", index=False)
print("Đã lưu data/interim/delhi_after_w4.csv và data/interim/gurugram_after_w4.csv (checkpoint, CHƯA phải bản nộp)")
print("W3 + W4 xong cho Delhi & Gurugram. Còn W5 (transform/encode nếu cần + merge) trước khi có data/processed/ thật.")

Đã lưu data/interim/delhi_after_w4.csv và data/interim/gurugram_after_w4.csv (checkpoint, CHƯA phải bản nộp)
W3 + W4 xong cho Delhi & Gurugram. Còn W5 (transform/encode nếu cần + merge) trước khi có data/processed/ thật.

## Bước 6: Đóng gói thành 1 lệnh + thử gộp (Integration)

Không scale/encode ở đây — theo nguyên tắc chống rò rỉ dữ liệu, việc đó phải
làm lúc build model (fit trên tập train), không áp cố định lên file dùng
chung. Vậy `data/processed/` dưới đây là **bản cuối cùng thật sự** cho phần
của bạn — giữ nguyên đơn vị gốc, dùng được cho cả EDA lẫn model sau này.

In [12]:
from utils import clean_city_pipeline

# 1 lệnh: raw -> đã làm sạch -> lưu data/processed/
delhi_final = clean_city_pipeline("Delhi", drop_cols=["Xylene"])
print()
gurugram_final = clean_city_pipeline("Gurugram", drop_cols=["Xylene"])

--- Xử lý Missing Values cho Delhi ---
  - CO: phát hiện 84 ngày flatline (0 liên tục >= 3 ngày) -> NaN
  - Benzene: phát hiện 3 ngày flatline (0 liên tục >= 3 ngày) -> NaN
  - Toluene: phát hiện 105 ngày flatline (0 liên tục >= 3 ngày) -> NaN
  - Xylene: phát hiện 128 ngày flatline (0 liên tục >= 3 ngày) -> NaN
  - Đã xoá cột (đề xuất, cần nhóm đồng ý): ['Xylene']
  => Còn 349 ô missing SAU xử lý (CHỦ Ý giữ NaN ở khối trống dài, không bịa số)
  - Consistency: không có vấn đề
  - Dòng trùng (City+Date): 0
  -> Đã lưu ../data/processed/delhi_clean.csv

--- Xử lý Missing Values cho Gurugram ---
  - NOx: phát hiện 23 ngày flatline (0 liên tục >= 3 ngày) -> NaN
  - CO: phát hiện 30 ngày flatline (0 liên tục >= 3 ngày) -> NaN
  - Benzene: phát hiện 264 ngày flatline (0 liên tục >= 3 ngày) -> NaN
  - Toluene: phát hiện 253 ngày flatline (0 liên tục >= 3 ngày) -> NaN
  - Đã xoá cột (đề xuất, cần nhóm đồng ý): ['Xylene']
  => Còn 4603 ô missing SAU xử lý (CHỦ Ý giữ NaN ở khối trống dài, không bịa số)
  - Consistency: không có vấn đề
  - Dòng trùng (City+Date): 0
  -> Đã lưu ../data/processed/gurugram_clean.csv

### Thử gộp (làm mẫu cho lúc có đủ 8 thành phố)

Chưa gộp được thật vì còn thiếu 6 thành phố kia — nhưng làm thử với 2 thành
phố mình có để phát hiện sớm các vấn đề khi gộp (đúng tinh thần slide: "print
len(df) trước/sau mỗi lần merge", và cột `City` đã đóng vai trò đánh dấu
"nguồn" rồi nên không cần thêm gì).

In [13]:
print("Delhi:", len(delhi_final), "dòng,", delhi_final.shape[1], "cột")
print("Gurugram:", len(gurugram_final), "dòng,", gurugram_final.shape[1], "cột")

combined_preview = pd.concat([delhi_final, gurugram_final], ignore_index=True)
print("Gộp lại:", len(combined_preview), "dòng  (phải =", len(delhi_final) + len(gurugram_final), ")")

# Kiểm tra lệch cột (schema mismatch) - giờ cả 2 cùng drop Xylene nên kỳ vọng KHÔNG còn lệch
only_delhi = set(delhi_final.columns) - set(gurugram_final.columns)
only_guru  = set(gurugram_final.columns) - set(delhi_final.columns)
print("\nCột chỉ có ở Delhi (không có ở Gurugram):", only_delhi)
print("Cột chỉ có ở Gurugram (không có ở Delhi):", only_guru)

Delhi: 2009 dòng, 39 cột
Gurugram: 1679 dòng, 39 cột
Gộp lại: 3688 dòng  (phải = 3688 )

Cột chỉ có ở Delhi (không có ở Gurugram): set()
Cột chỉ có ở Gurugram (không có ở Delhi): set()

✅ **Đã sửa theo bằng chứng 8 thành phố:** cả Delhi và Gurugram giờ cùng drop
`Xylene`, cùng giữ `NH3` → 2 bảng có chung schema, không còn lệch cột khi gộp.
Đây là đề xuất đã có bằng chứng cụ thể (bảng %missing 8 thành phố ở Bước 2),
nhóm chỉ cần xác nhận lại là dùng được ngay cho cả 8 thành phố.

In [14]:
os.makedirs("../data/processed", exist_ok=True)
combined_preview.to_csv("../data/processed/air_quality_delhi_gurugram_preview.csv", index=False)
print("Đã lưu data/processed/air_quality_delhi_gurugram_preview.csv (bản xem trước, không phải bản gộp 8 thành phố cuối cùng)")

Đã lưu data/processed/air_quality_delhi_gurugram_preview.csv (bản xem trước, không phải bản gộp 8 thành phố cuối cùng)